name: behavioral-cloning
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.5.2
    - numpy
    - matplotlib
    - opencv3
    - h5py
    - flask-socketio
    - scikit-learn
    - ffmpeg
    - imageio=2.1.2
    - pandas
    - pip:
        - tensorflow==0.12.1
        - keras==1.2.1
