name: behavioral-cloning
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.5.2
    - numpy
    - matplotlib
    - opencv3
    - h5py
    - flask-socketio
    - scikit-learn
    - ffmpeg
    - imageio=2.1.2
    - pandas
    - pip:
        - https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-0.12.1-cp35-cp35m-linux_x86_64.whl
        - keras==1.2.1
